# Generated by Django 4.2 on 2023-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Ментор', 'verbose_name_plural': 'Менторы'},
        ),
        migrations.AlterModelOptions(
            name='mentorreview',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
