version: '3'

services:
  db:
    image: "postgres:15"
    hostname: mentor_host
    environment:
      - POSTGRES_DB=mentor
      - POSTGRES_USER=mentor_user
      - POSTGRES_PASSWORD=772007
    ports:
      - "5434:5432"
    volumes:
      - dist-postgres-database:/var/lib/postgresql/data

  mentor:
    build:
      context: .
    env_file:
      - .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./static:/mentor/static
      - ./media:/mentor/media
volumes:
  dist-postgres-database: