# Generated by Django 4.2 on 2023-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
